'use client'

import { useState } from 'react'
import { statementPdfUrl } from '@blackfire/api-client'
import type { ScheduledStatement } from '@blackfire/types'

const money = (value: number) => `R ${Number(value ?? 0).toLocaleString('en-ZA', { minimumFractionDigits: 2 })}`

export default function StatementLog({ rows }: { rows: ScheduledStatement[] }) {
  const [preview, setPreview] = useState<ScheduledStatement | null>(null)
  return <div className="mx-auto max-w-7xl">
    <header className="mb-8"><p className="text-[11px] uppercase tracking-[0.28em] text-fire-orange">Finance / Statements</p><h1 className="mt-2 font-display text-5xl text-ink-text">Statement Log</h1><p className="mt-2 text-sm text-ash">Scheduler-generated account statements, branded by issuing company.</p></header>
    <div className="grid gap-4 lg:grid-cols-2">{rows.length ? rows.map(row => <article key={row.id} className="border border-[#ccc] border-l-2 border-l-fire-orange bg-white p-5">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs text-fire-orange">{row.ref_id}</p><h2 className="mt-2 font-display text-2xl text-ink-text">{row.company_name}</h2></div><span className={`rounded-full px-3 py-1 font-mono text-[9px] uppercase tracking-[0.12em] ${row.status === 'released' ? 'bg-success/10 text-success' : 'bg-warning/10 text-warning'}`}>{row.status.replace('_', ' ')}</span></div>
      <div className="mt-5 grid gap-3 border-y border-[#ddd] py-4 sm:grid-cols-3"><div><p className="text-[9px] uppercase tracking-[0.16em] text-ash">Statement date</p><p className="mt-1 text-sm text-ink-text">{row.scheduled_for.slice(0, 10)}</p></div><div><p className="text-[9px] uppercase tracking-[0.16em] text-ash">Invoices</p><p className="mt-1 text-sm text-ink-text">{row.invoice_refs ? row.invoice_refs.split(',').length : 0}</p></div><div><p className="text-[9px] uppercase tracking-[0.16em] text-ash">Outstanding</p><p className="mt-1 font-semibold text-ink-text">{money(row.total_outstanding)}</p></div></div>
      <div className="mt-4 grid gap-2 sm:grid-cols-2"><button type="button" onClick={() => setPreview(row)} className="border border-fire-orange px-4 py-3 text-center text-[11px] font-semibold uppercase tracking-[0.16em] text-fire-orange">View</button><a href={statementPdfUrl(row.ref_id)} className="bg-fire-orange px-4 py-3 text-center text-[11px] font-semibold uppercase tracking-[0.16em] text-white">Download PDF</a></div>
    </article>) : <p className="border border-[#ccc] bg-white p-10 text-center text-sm text-ash lg:col-span-2">No statements found.</p>}</div>
    {preview && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 p-3 sm:p-8" role="dialog" aria-modal="true" aria-labelledby="statement-preview-title" onMouseDown={event => { if (event.target === event.currentTarget) setPreview(null) }}>
      <div className="max-h-[92vh] w-full max-w-4xl overflow-y-auto bg-[#f4f0e6] shadow-2xl">
        <header className="sticky top-0 z-10 flex items-center justify-between border-b border-[#ccc] bg-white px-5 py-4"><div><p className="text-[9px] uppercase tracking-[0.18em] text-ash">Statement preview</p><h2 id="statement-preview-title" className="font-display text-2xl text-ink-text">{preview.ref_id}</h2></div><button type="button" onClick={() => setPreview(null)} className="h-11 w-11 border border-[#ccc] text-2xl text-ash" aria-label="Close preview">×</button></header>
        <div className="bg-[#0A1626] p-6 text-white sm:p-8"><div className="flex flex-wrap items-start justify-between gap-6"><div><p className="text-[10px] uppercase tracking-[0.3em] text-[#C2A04A]">{preview.company_name}</p><p className="mt-3 font-display text-3xl">Account Statement</p></div><div className="text-right"><p className="font-mono text-[9px] uppercase tracking-[0.16em] text-[#C2A04A]">Reference</p><p className="mt-2 font-mono text-xl font-bold">{preview.ref_id}</p></div></div></div>
        <div className="p-5 sm:p-8"><div className="grid gap-4 border-b border-[#dcd3bf] pb-5 sm:grid-cols-4"><div><p className="text-[9px] uppercase tracking-[0.16em] text-ash">Statement date</p><p className="mt-2 text-sm">{preview.scheduled_for.slice(0, 10)}</p></div><div><p className="text-[9px] uppercase tracking-[0.16em] text-ash">Issuer</p><p className="mt-2 text-sm">{preview.company_name}</p></div><div><p className="text-[9px] uppercase tracking-[0.16em] text-ash">Status</p><p className="mt-2 text-sm capitalize">{preview.status.replace('_', ' ')}</p></div><div><p className="text-[9px] uppercase tracking-[0.16em] text-ash">Invoices</p><p className="mt-2 text-sm">{preview.invoice_refs ? preview.invoice_refs.split(',').length : 0}</p></div></div><div className="mt-6"><p className="text-[9px] uppercase tracking-[0.16em] text-ash">Invoice references</p><p className="mt-2 break-words font-mono text-xs leading-6 text-ink-text">{preview.invoice_refs || 'None'}</p></div><div className="mt-6 flex flex-wrap items-center justify-between gap-4 border-y-2 border-[#0A1626] py-5"><span className="font-display text-2xl text-ink-text">Total Outstanding</span><strong className="font-display text-3xl text-ink-text">{money(preview.total_outstanding)}</strong></div><div className="mt-6 flex justify-end"><a href={statementPdfUrl(preview.ref_id)} className="bg-fire-orange px-5 py-3 text-[11px] font-semibold uppercase tracking-[0.16em] text-white">Download PDF</a></div></div>
      </div>
    </div>}
  </div>
}
