# BlackFire - Full-stack dev environment
# Starts: PHP portal (:8080) + Next.js web app (:3000) + Expo mobile (optional)
# Usage:
#   .\start-dev.ps1         # PHP + Next.js only
#   .\start-dev.ps1 -Mobile # PHP + Next.js + Expo
#
# Prereqs:
#   php.exe on PATH (PHP 8.x)
#   node/pnpm on PATH
#   npx/expo-cli available
#   .env in BlackFire Portal\ (copy from .env.example if missing)

param([switch]$Mobile)

$ErrorActionPreference = 'Stop'

$root = $PSScriptRoot
$portalPath = Join-Path $root 'BlackFire Portal'
$webPath = Join-Path $root 'apps\web'
$mobilePath = Join-Path $root 'apps\mobile'
$envPath = Join-Path $root 'BlackFire Portal\.env'
$envExample = Join-Path $root 'BlackFire Portal\.env.example'

# Guard: .env must exist before we start anything.
if (-not (Test-Path -LiteralPath $envPath)) {
  if (Test-Path -LiteralPath $envExample) {
    Write-Host '[setup] Copying .env.example -> .env; fill in real values before running again.' -ForegroundColor Yellow
    Copy-Item -LiteralPath $envExample -Destination $envPath
    Write-Host "[setup] Edit '$envPath' then re-run this script." -ForegroundColor Yellow
    exit 1
  }

  Write-Host "[error] No .env found at '$envPath'. Aborting." -ForegroundColor Red
  exit 1
}

# Guard: create the Next.js API mirror when it does not exist.
$webEnvLocal = Join-Path $webPath '.env.local'
if (-not (Test-Path -LiteralPath $webEnvLocal)) {
@"
# Auto-generated by start-dev.ps1
# Points the Next.js web app at the local PHP dev server
NEXT_PUBLIC_API_BASE=http://localhost:8080/api
"@ | Out-File -FilePath $webEnvLocal -Encoding utf8
  Write-Host "[setup] Created $webEnvLocal -> Next.js will use the local PHP API." -ForegroundColor Cyan
}

Write-Host ''
Write-Host 'Starting PHP portal on http://localhost:8080 ...' -ForegroundColor Cyan

$phpJob = Start-Job -ScriptBlock {
  param($path)
  Set-Location -LiteralPath $path
  & php -S localhost:8080 -t . 2>&1
} -ArgumentList $portalPath
Write-Host "[php]    Job ID $($phpJob.Id)" -ForegroundColor DarkGray

# Brief wait to let PHP bind before Next.js tries to call it on first request.
Start-Sleep -Milliseconds 800

Write-Host 'Starting Next.js web app on http://localhost:3000 ...' -ForegroundColor Cyan

$nextJob = Start-Job -ScriptBlock {
  param($path)
  Set-Location -LiteralPath $path
  & pnpm exec next dev -p 3000 2>&1
} -ArgumentList $webPath
Write-Host "[next]   Job ID $($nextJob.Id)" -ForegroundColor DarkGray

$expoJob = $null
if ($Mobile) {
  Write-Host 'Starting Expo mobile app ...' -ForegroundColor Cyan
  $expoJob = Start-Job -ScriptBlock {
    param($path)
    Set-Location -LiteralPath $path
    & npx expo start 2>&1
  } -ArgumentList $mobilePath
  Write-Host "[expo]   Job ID $($expoJob.Id)" -ForegroundColor DarkGray
}

Write-Host ''
Write-Host '----------------------------------------' -ForegroundColor DarkGray
Write-Host ' PHP portal   -> http://localhost:8080' -ForegroundColor White
Write-Host ' Web app      -> http://localhost:3000' -ForegroundColor White
if ($Mobile) {
  Write-Host ' Expo         -> see Expo DevTools (QR in terminal)' -ForegroundColor White
}
Write-Host '----------------------------------------' -ForegroundColor DarkGray
Write-Host ' Press Ctrl+C to stop all services.' -ForegroundColor DarkGray
Write-Host ''

# Stream output from the background jobs until the user stops the session.
$jobs = @($phpJob, $nextJob)
if ($expoJob) {
  $jobs += $expoJob
}
$prefixes = @('[php] ', '[next]', '[expo]')

try {
  while ($true) {
    for ($i = 0; $i -lt $jobs.Count; $i++) {
      $job = $jobs[$i]
      $prefix = $prefixes[$i]
      $lines = Receive-Job -Job $job 2>&1
      foreach ($line in $lines) {
        if ($line) {
          Write-Host "$prefix $line" -ForegroundColor DarkGray
        }
      }
    }

    Start-Sleep -Milliseconds 500
  }
}
finally {
  Write-Host ''
  Write-Host 'Stopping all services...' -ForegroundColor Yellow
  foreach ($job in $jobs) {
    Stop-Job -Job $job -ErrorAction SilentlyContinue
    Remove-Job -Job $job -Force -ErrorAction SilentlyContinue
  }
  Write-Host 'Done.' -ForegroundColor Green
}
