// Generated by scripts/sync-umlilo-contracts.ps1
// Source: BlackFire/contracts/portal.contract.json
// Do not edit this file directly.

export type Role =
  | 'sysadmin'
  | 'admin'
  | 'manager'
  | 'finance'
  | 'safety_officer'
  | 'viewer'
  | 'client'
  | 'inspector'
  | 'client_support'
  | 'junior_tech'
  | 'senior_tech'
  | 'call_logger'
  | 'admin_clerk'

export type CalloutPriority =
  | 'Normal'
  | 'Urgent'
  | 'Emergency'

export type CalloutStatus =
  | 'Open'
  | 'In Progress'
  | 'Completed'
  | 'Invoiced'
  | 'Cancelled'

export type QuoteStatus =
  | 'Draft'
  | 'Sent'
  | 'Pending Approval'
  | 'Approved'
  | 'Rejected'
  | 'Expired'
  | 'Converted'
  | 'Reversed'

export type InvoiceStatus =
  | 'Draft'
  | 'Sent'
  | 'Paid'
  | 'Overdue'
  | 'Cancelled'

export type SafetyFileStatus =
  | 'Draft'
  | 'In Progress'
  | 'Submitted'
  | 'Approved'

export type SafetyItemResult =
  | 'N/A'
  | 'Not to Standard'
  | 'To Standard'

export type SafetyItemApStatus =
  | 'Open'
  | 'In Progress'
  | 'Resolved'

export type ApprovalStatus =
  | 'not_required'
  | 'pending'
  | 'approved'
  | 'rejected'

export type QuoteApprovalStatus =
  | 'pending'
  | 'approved'
  | 'rejected'

export type ComplianceLevel =
  | 'RED'
  | 'ORANGE'
  | 'YELLOW'
  | 'GREEN'

export type TransactionType =
  | 'credit'
  | 'debit'

export type TaskCategory =
  | 'admin'
  | 'sales'
  | 'general'

export type TaskStatus =
  | 'Open'
  | 'In Progress'
  | 'Done'
  | 'Cancelled'

export type TaskPriority =
  | 'Low'
  | 'Normal'
  | 'High'
  | 'Urgent'

export interface User {
  id: number
  username: string
  name: string
  email: string
  role: Role
  roles: Role[]
  permissions: string[]
  client_id: number | null
  active: boolean
  created_at: string
  last_login: string | null
}

export interface AuthResponse {
  success: boolean
  user?: User
  token?: string
  message?: string
}

export interface Callout {
  id: number
  ref_id: string
  client_id: number | null
  client_name: string
  service: string
  location: string
  priority: CalloutPriority
  status: CalloutStatus
  approval_status: ApprovalStatus
  assigned_to: string | null
  callout_date: string
  callout_time: string | null
  notes: string | null
  start_at: string | null
  end_at: string | null
  due_at: string | null
  created_by: string
  created_at: string
  updated_at: string
}

export interface QuoteItem {
  id: number
  quote_id: number
  description: string
  qty: number
  unit_price: number
  total: number
}

export interface Quote {
  id: number
  ref_id: string
  quote_number: string
  client_id: number
  client_name: string
  client_email: string
  company_profile_id: number
  vat_rate: number
  callout_id: number | null
  callout_ref: string | null
  status: QuoteStatus
  approval_status: QuoteApprovalStatus | null
  subtotal: number
  tax: number
  total: number
  valid_until: string
  notes: string | null
  items: QuoteItem[]
  created_by: string
  created_at: string
  reversal_request_id?: number | null
  reversal_status?: 'pending' | 'approved' | 'rejected' | null
  reversal_reason?: string | null
  reversal_requested_at?: string | null
}

export interface Invoice {
  id: number
  ref_id?: string
  invoice_number: string
  client_id: number
  client_name: string
  company_profile_id: number
  vat_rate: number
  quote_id: number | null
  quote_ref?: string | null
  callout_id?: number | null
  callout_ref?: string | null
  amount: number
  tax: number
  total: number
  status: InvoiceStatus
  due_date: string
  paid_date: string | null
  notes: string | null
  created_by: string
  created_at: string
  reversal_request_id?: number | null
  reversal_status?: 'pending' | 'approved' | 'rejected' | null
  reversal_reason?: string | null
  reversal_requested_at?: string | null
  reversal_requested_by?: string | null
  reversal_decided_by?: string | null
}

export interface Client {
  id: number
  name: string
  contact_person: string | null
  email: string | null
  phone: string | null
  address: string | null
  site: string | null
  active: boolean
  created_at: string
}

export interface SafetyItem {
  id: number
  file_id: number
  section: string
  item_number: number
  description: string
  result: SafetyItemResult
  ap_status: SafetyItemApStatus
  comment: string | null
  evidence_path: string | null
  updated_at: string
}

export interface SafetyFile {
  id: number
  ref_id: string
  client_id: number
  client_name: string
  site: string
  status: SafetyFileStatus
  score: number
  total_items: number
  score_percent: number
  compliance_level: ComplianceLevel
  submitted_by: string | null
  approved_by: string | null
  submitted_at: string | null
  approved_at: string | null
  created_at: string
  items?: SafetyItem[]
}

export interface Transaction {
  id: number
  client_id: number
  invoice_id: number | null
  type: TransactionType
  amount: number
  description: string
  transaction_date: string
  created_at: string
}

export interface Payment {
  id: number
  invoice_id: number
  amount: number
  method: string
  reference: string | null
  payment_date: string
  created_at: string
}

export interface Statement {
  client_id: number
  client_name: string
  period_start: string
  period_end: string
  opening_balance: number
  total_invoiced: number
  total_paid: number
  closing_balance: number
  transactions: Transaction[]
}

export interface TaskAssignee {
  user_id: number
  username: string
  name: string
}

export interface TaskAssignableUser {
  id: number
  username: string
  name: string
  role: Role
}

export interface ScheduledStatement {
  id: number
  ref_id: string
  company_profile_id: number
  company_name: string
  client_name: string
  scheduled_for: string
  status: 'pending_approval' | 'released' | 'cancelled'
  from_email: string
  to_emails: string
  invoice_refs: string
  total_outstanding: number
  released_by: string
  released_at: string | null
  created_at: string
}

export interface CompanyProfile {
  id: number
  profile_key: string
  display_name: string
  legal_name: string
  registration_number: string
  vat_number: string
  phone: string
  email: string
  address: string
  logo_path: string
  bank_name: string
  bank_account_type: string
  bank_account_number: string
  bank_branch_code: string
  bank_swift_code: string
  currency_code: string
  vat_rate: number
  quote_prefix: string
  invoice_prefix: string
}

export interface ClientDocumentProfile {
  id: number
  client_id: number
  profile_key: string
  display_name: string
  legal_name: string
  vat_number: string
  phone: string
  email: string
  quote_address: string
  invoice_address: string
  supplier_reference: string
  purchase_order_prefix: string
}

export interface DocumentTemplate {
  id: number
  company_profile_id: number
  company_name: string
  template_key: string
  template_type: 'quote' | 'invoice' | 'statement' | 'email'
  name: string
  description: string
  version: number
}

export interface DashboardKPIs {
  open_tasks: number
  urgent_tasks: number
  tasks_due_today: number
  open_callouts: number
  urgent_callouts: number
  overdue_invoices: number
  mtd_revenue: number
  safety_score: number | null
  pending_quotes: number
  pending_statements: number
  active_clients: number
}

export interface DashboardAmountSummary {
  invoiced: number
  outstanding: number
  net_cash_movement: number
  quote_pipeline: number
}

export interface DashboardRunRateMonth {
  label: string
  month: string
  count: number
  amount: number
}

export interface DashboardRunRate {
  period_label: string
  period_start: string
  period_end: string
  average_count: number
  average_amount: number
  total_count: number
  total_amount: number
  months: DashboardRunRateMonth[]
}

export interface DashboardCashComparison {
  key: 'mtd' | 'qtd' | 'ytd'
  label: string
  current: number
  previous: number
  change_percent: number | null
}

export interface DashboardDueSoonRecord {
  record_type: 'Task' | 'Callout' | 'Invoice' | 'Quote'
  ref_id: string
  record_title: string
  assignee: string
  due_date: string
}

export interface DashboardUsageRow {
  username: string
  name: string
  last_login: string | null
  last_activity: string | null
  current_logins: number
  previous_logins: number
  page_views: number
  actions: number
}

export interface DashboardData {
  data: DashboardKPIs
  amounts: DashboardAmountSummary
  invoice_run_rate: DashboardRunRate
  cash_comparisons: DashboardCashComparison[]
  due_soon: DashboardDueSoonRecord[]
  usage: DashboardUsageRow[]
  usage_period_days: number
  recent_tasks: Pick<Task, 'ref_id' | 'category' | 'title' | 'status' | 'priority' | 'assigned_to' | 'due_date' | 'source_callout_ref' | 'created_at'>[]
  task_streams: TaskStreamCounts
  recent_callouts: { ref_id: string; client_name: string; service: string; status: string; priority: string; callout_date: string | null }[]
  monthly_revenue: { label: string; value: number }[]
}

export interface DashboardResponse extends DashboardData {
  success: boolean
}

export interface AuditEvent {
  id: number
  user_id: number
  username: string
  action: string
  entity: string
  entity_id: number | null
  detail: string | null
  ip: string | null
  created_at: string
}

export interface ApiResponse<T = unknown> {
  success: boolean
  data?: T
  message?: string
  errors?: Record<string, string>
}

export interface PaginatedResponse<T> extends ApiResponse<T[]> {
  total: number
  page: number
  per_page: number
}

export interface Task {
  id: number
  ref_id: string
  category: TaskCategory
  title: string
  description: string | null
  status: TaskStatus
  priority: TaskPriority
  assigned_to_user_id: number | null
  assigned_to: string | null
  assignee_name: string | null
  assignees?: TaskAssignee[]
  created_by_user_id: number
  created_by: string
  creator_name: string | null
  source_callout_ref: string | null
  due_date: string | null
  start_at: string | null
  end_at: string | null
  due_at: string | null
  completed_at: string | null
  created_at: string
  updated_at: string
}

export interface TaskListResponse extends ApiResponse<Task[]> {
  total: number
  page: number
  limit: number
  categories: TaskCategory[]
}

export interface TaskStreamCounts {
  admin: number
  sales: number
  general: number
}

export interface TrackerUpdate {
  id: number
  label: string
  content: string
  source_kind: string
  created_by: string
  updated_by: string | null
  created_at: string
  updated_at: string
  revision_count: number
}

export interface TrackerUpdateRevision {
  id: number
  old_label: string
  old_content: string
  new_label: string
  new_content: string
  edited_by: string
  edited_at: string
}

export interface Attachment {
  id: number
  original_name: string
  file_size: number
  mime_type: string
  uploaded_by: string
  created_at: string
}

export interface DigitalSignature {
  id: number
  document_label: string
  document_hash: string
  signed_document_ref: string | null
  token: string
  token_expires_at: string
  status: string
  signer_role: string
  signer_company: string | null
  signer_email: string
  signer_ip: string | null
  signature_method: string | null
  signature_image: string | null
  certificate_subject: string | null
  certificate_issuer: string | null
  certificate_serial: string | null
  sent_at: string | null
  signed_at: string | null
  declined_at: string | null
  declined_reason: string | null
  created_at: string
  updated_at: string
}
