table Payments
	lineageTag: b6000000-0000-4000-8000-000000000001

	column id
		dataType: int64
		formatString: 0
		lineageTag: b6000000-0000-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: id

	column invoice_id
		dataType: int64
		formatString: 0
		lineageTag: b6000000-0000-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: invoice_id

	column amount
		dataType: double
		formatString: \R#,0.00
		lineageTag: b6000000-0000-4000-8000-000000000004
		summarizeBy: sum
		sourceColumn: amount

	column payment_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: b6000000-0000-4000-8000-000000000006
		summarizeBy: none
		sourceColumn: payment_date

	column payment_ref
		dataType: string
		lineageTag: b6000000-0000-4000-8000-000000000007
		summarizeBy: none
		sourceColumn: payment_ref

	column client_id
		dataType: int64
		formatString: 0
		lineageTag: b6000000-0000-4000-8000-000000000008
		summarizeBy: none
		sourceColumn: client_id

	partition Payments = m
		mode: import
		source =
				let
					Source = MySQL.Database(#"Database Server", #"Database Name", [ReturnSingleDatabase=true]),
					Data = Source{[Schema=#"Database Name",Item="bf_payments"]}[Data],
					Selected = Table.SelectColumns(Data, {"id", "payment_ref", "invoice_id", "client_id", "amount", "payment_date"}, MissingField.UseNull),
					Typed = Table.TransformColumnTypes(Selected, {{"amount", type number}, {"payment_date", type datetime}})
				in
					Typed

	annotation PBI_ResultType = Table

