table SafetyFiles
	lineageTag: ba000000-0000-4000-8000-000000000001

	column id
		dataType: int64
		formatString: 0
		lineageTag: ba000000-0000-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: id

	column ref_id
		dataType: string
		lineageTag: ba000000-0000-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: ref_id

	column contractor
		dataType: string
		lineageTag: ba000000-0000-4000-8000-000000000004
		summarizeBy: none
		sourceColumn: contractor

	column audit_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: ba000000-0000-4000-8000-000000000005
		summarizeBy: none
		sourceColumn: audit_date

	column region
		dataType: string
		lineageTag: ba000000-0000-4000-8000-000000000006
		summarizeBy: none
		sourceColumn: region

	column status
		dataType: string
		lineageTag: ba000000-0000-4000-8000-000000000007
		summarizeBy: none
		sourceColumn: status

	column is_active
		dataType: int64
		formatString: 0
		lineageTag: ba000000-0000-4000-8000-000000000008
		summarizeBy: sum
		sourceColumn: is_active

		annotation SummarizationSetBy = Automatic

	column score
		dataType: double
		formatString: 0.0
		lineageTag: ba000000-0000-4000-8000-000000000009
		summarizeBy: average
		sourceColumn: score

	column band
		dataType: string
		lineageTag: ba000000-0000-4000-8000-00000000000a
		summarizeBy: none
		sourceColumn: band

	partition SafetyFiles = m
		mode: import
		source =
				let
					Source = MySQL.Database(#"Database Server", #"Database Name", [ReturnSingleDatabase=true]),
					Data = Source{[Schema=#"Database Name",Item="bf_safety_files"]}[Data],
					Selected = Table.SelectColumns(Data, {"id", "ref_id", "contractor", "audit_date", "region", "status", "is_active", "score", "band"}, MissingField.UseNull),
					Typed = Table.TransformColumnTypes(Selected, {{"score", type number}, {"audit_date", type datetime}, {"is_active", Int64.Type}})
				in
					Typed

	annotation PBI_ResultType = Table

