table Users
	isHidden
	lineageTag: b7000000-0000-4000-8000-000000000001

	column id
		dataType: int64
		formatString: 0
		lineageTag: b7000000-0000-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: id

	column username
		dataType: string
		lineageTag: b7000000-0000-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: username

	column email
		dataType: string
		lineageTag: b7000000-0000-4000-8000-000000000004
		summarizeBy: none
		sourceColumn: email

	column role
		dataType: string
		lineageTag: b7000000-0000-4000-8000-000000000005
		summarizeBy: none
		sourceColumn: role

	column client_id
		dataType: int64
		formatString: 0
		lineageTag: b7000000-0000-4000-8000-000000000006
		summarizeBy: none
		sourceColumn: client_id

	partition Users = m
		mode: import
		source =
				let
					Source = MySQL.Database(#"Database Server", #"Database Name", [ReturnSingleDatabase=true]),
					Data = Source{[Schema=#"Database Name",Item="bf_users"]}[Data],
					Selected = Table.SelectColumns(Data, {"id", "username", "email", "role", "client_id"}, MissingField.UseNull)
				in
					Selected

	annotation PBI_ResultType = Table

