table Clients
	lineageTag: b2000000-0000-4000-8000-000000000001

	column id
		dataType: int64
		formatString: 0
		lineageTag: b2000000-0000-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: id

	column name
		dataType: string
		lineageTag: b2000000-0000-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: name

	column contact_person
		dataType: string
		lineageTag: b2000000-0000-4000-8000-000000000004
		summarizeBy: none
		sourceColumn: contact_person

	column email
		dataType: string
		lineageTag: b2000000-0000-4000-8000-000000000005
		summarizeBy: none
		sourceColumn: email

	column is_active
		dataType: int64
		formatString: 0
		lineageTag: b2000000-0000-4000-8000-000000000007
		summarizeBy: sum
		sourceColumn: is_active

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: b2000000-0000-4000-8000-000000000008
		summarizeBy: none
		sourceColumn: created_at

	partition Clients = m
		mode: import
		source =
				let
					Source = MySQL.Database(#"Database Server", #"Database Name", [ReturnSingleDatabase=true]),
					Data = Source{[Schema=#"Database Name",Item="bf_clients"]}[Data],
					Selected = Table.SelectColumns(Data, {"id", "name", "contact_person", "email", "is_active", "created_at"}, MissingField.UseNull),
					Typed = Table.TransformColumnTypes(Selected, {{"is_active", Int64.Type}})
				in
					Typed

	annotation PBI_ResultType = Table

