table Tasks
	lineageTag: bb000000-0000-4000-8000-000000000001

	column id
		dataType: int64
		formatString: 0
		lineageTag: bb000000-0000-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: id

	column ref_id
		dataType: string
		lineageTag: bb000000-0000-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: ref_id

	column category
		dataType: string
		lineageTag: bb000000-0000-4000-8000-000000000004
		summarizeBy: none
		sourceColumn: category

	column title
		dataType: string
		lineageTag: bb000000-0000-4000-8000-000000000005
		summarizeBy: none
		sourceColumn: title

	column status
		dataType: string
		lineageTag: bb000000-0000-4000-8000-000000000006
		summarizeBy: none
		sourceColumn: status

	column priority
		dataType: string
		lineageTag: bb000000-0000-4000-8000-000000000007
		summarizeBy: none
		sourceColumn: priority

	column assigned_to
		dataType: string
		lineageTag: bb000000-0000-4000-8000-000000000008
		summarizeBy: none
		sourceColumn: assigned_to

	column due_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: bb000000-0000-4000-8000-000000000009
		summarizeBy: none
		sourceColumn: due_date

	column completed_at
		dataType: dateTime
		formatString: General Date
		lineageTag: bb000000-0000-4000-8000-00000000000a
		summarizeBy: none
		sourceColumn: completed_at

	partition Tasks = m
		mode: import
		source =
				let
					Source = MySQL.Database(#"Database Server", #"Database Name", [ReturnSingleDatabase=true]),
					Data = Source{[Schema=#"Database Name",Item="bf_tasks"]}[Data],
					Selected = Table.SelectColumns(Data, {"id", "ref_id", "category", "title", "status", "priority", "assigned_to", "due_date", "completed_at"}, MissingField.UseNull),
					Typed = Table.TransformColumnTypes(Selected, {{"due_date", type datetime}})
				in
					Typed

	annotation PBI_ResultType = Table

