param(
    [string]$WorkspaceRoot
)

$ErrorActionPreference = 'Stop'

if (-not $WorkspaceRoot) {
    $WorkspaceRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
} else {
    $WorkspaceRoot = Resolve-Path $WorkspaceRoot
}

$contractPath = Join-Path $WorkspaceRoot 'BlackFire\contracts\portal.contract.json'
$tokensPath = Join-Path $WorkspaceRoot 'BlackFire\contracts\umlilo.tokens.json'
$typesOut = Join-Path $WorkspaceRoot 'BlackFire\packages\types\index.ts'
$tokensOut = Join-Path $WorkspaceRoot 'BlackFire\packages\ui-tokens\index.ts'

function Read-JsonFile {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Missing contract file: $Path"
    }
    return Get-Content -Raw -LiteralPath $Path | ConvertFrom-Json
}

function Quote-TsString {
    param([string]$Value)
    return "'" + ($Value -replace "'", "\\'") + "'"
}

function Format-TsKey {
    param([string]$Key)
    if ($Key -match '^[A-Za-z_$][A-Za-z0-9_$]*$') {
        return $Key
    }
    return Quote-TsString $Key
}

function Write-Utf8NoBom {
    param(
        [string]$Path,
        [string[]]$Lines
    )
    $encoding = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, (($Lines -join "`n") + "`n"), $encoding)
}

function Add-Blank {
    param([System.Collections.Generic.List[string]]$Lines)
    [void]$Lines.Add('')
}

function Generate-Types {
    param(
        [object]$Contract,
        [string]$Path
    )

    $lines = New-Object 'System.Collections.Generic.List[string]'
    [void]$lines.Add('// Generated by scripts/sync-umlilo-contracts.ps1')
    [void]$lines.Add('// Source: BlackFire/contracts/portal.contract.json')
    [void]$lines.Add('// Do not edit this file directly.')
    Add-Blank $lines

    foreach ($enum in $Contract.enums.PSObject.Properties) {
        [void]$lines.Add("export type $($enum.Name) =")
        foreach ($value in $enum.Value) {
            [void]$lines.Add("  | $(Quote-TsString $value)")
        }
        Add-Blank $lines
    }

    foreach ($interface in $Contract.interfaces.PSObject.Properties) {
        [void]$lines.Add("export interface $($interface.Name) {")
        foreach ($field in $interface.Value.PSObject.Properties) {
            [void]$lines.Add("  $($field.Name): $($field.Value)")
        }
        [void]$lines.Add('}')
        Add-Blank $lines
    }

    if ($lines.Count -gt 0 -and $lines[$lines.Count - 1] -eq '') {
        $lines.RemoveAt($lines.Count - 1)
    }
    Write-Utf8NoBom -Path $Path -Lines $lines
}

function Generate-Tokens {
    param(
        [object]$Tokens,
        [string]$Path
    )

    $lines = New-Object 'System.Collections.Generic.List[string]'
    [void]$lines.Add('// Generated by scripts/sync-umlilo-contracts.ps1')
    [void]$lines.Add('// Source: BlackFire/contracts/umlilo.tokens.json')
    [void]$lines.Add('// Do not edit this file directly.')
    Add-Blank $lines

    [void]$lines.Add('export const colors = {')
    foreach ($color in $Tokens.colors.PSObject.Properties) {
        [void]$lines.Add("  $(Format-TsKey $color.Name): $(Quote-TsString $color.Value),")
    }
    [void]$lines.Add('} as const')
    Add-Blank $lines

    [void]$lines.Add('export const themes = {')
    foreach ($theme in $Tokens.themes.PSObject.Properties) {
        [void]$lines.Add("  $(Format-TsKey $theme.Name): {")
        foreach ($token in $theme.Value.PSObject.Properties) {
            [void]$lines.Add("    $(Format-TsKey $token.Name): $(Quote-TsString $token.Value),")
        }
        [void]$lines.Add('  },')
    }
    [void]$lines.Add('} as const')
    [void]$lines.Add('export type ThemeMode = keyof typeof themes')
    [void]$lines.Add('export type ThemePalette = (typeof themes)[ThemeMode]')
    Add-Blank $lines

    [void]$lines.Add('export const fonts = {')
    foreach ($font in $Tokens.fonts.PSObject.Properties) {
        [void]$lines.Add("  $(Format-TsKey $font.Name): $(Quote-TsString $font.Value),")
    }
    [void]$lines.Add('} as const')
    Add-Blank $lines

    [void]$lines.Add('export const spacing = {')
    foreach ($space in $Tokens.spacing.PSObject.Properties) {
        [void]$lines.Add("  $(Format-TsKey $space.Name): $($space.Value),")
    }
    [void]$lines.Add('} as const')
    Add-Blank $lines

    [void]$lines.Add('export const tailwindTokens = {')
    [void]$lines.Add('  colors: {')
    foreach ($mapping in $Tokens.tailwindColors.PSObject.Properties) {
        [void]$lines.Add("    $(Format-TsKey $mapping.Name): colors.$($mapping.Value),")
    }
    [void]$lines.Add('  },')
    [void]$lines.Add('  fontFamily: {')
    foreach ($font in $Tokens.fonts.PSObject.Properties) {
        $fallback = 'sans-serif'
        if ($Tokens.PSObject.Properties.Name -contains 'fontFallbacks') {
            $fallbackProp = $Tokens.fontFallbacks.PSObject.Properties[$font.Name]
            if ($fallbackProp) {
                $fallback = $fallbackProp.Value
            }
        }
        [void]$lines.Add("    $(Format-TsKey $font.Name): [fonts.$($font.Name), $(Quote-TsString $fallback)],")
    }
    [void]$lines.Add('  },')
    [void]$lines.Add('} as const')

    Write-Utf8NoBom -Path $Path -Lines $lines
}

$contract = Read-JsonFile $contractPath
$tokens = Read-JsonFile $tokensPath

Generate-Types -Contract $contract -Path $typesOut
Generate-Tokens -Tokens $tokens -Path $tokensOut

Write-Host "Generated shared types: $typesOut"
Write-Host "Generated UI tokens: $tokensOut"
